### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by diaodiao317** [yiping-wang/c2am#10]
Hello author, I read your paper and feel that the idea is very good. Recently, I tried to reproduce the effect of your model. At first I tried to retrain your model by myself, but the generated c2am effect is always around 44-45, I tried to download your baseline weight and global_CAM_BY_CLASS from your network disk, and then use these two to retrain the model, But the effect is still around 45. But I tried to verify it with the c2am.pth you provided, and the result is around 51 as you reported. I don't know where the problem is. Do you have any additional operations and steps when training c2am? Looking forward to your answer, thanks.
如果方便的话你也可以用中文回答我，万分感谢。

**Comment by yiping-wang** [comment]
It was resolved as the `global_cam` was initialized wrong. Quote from the OP 

> 我找到问题所在了，由于目录问题，globalcam那个文件没有读进去被自动初始化成全zero了。还是万分感谢作者回复😊。
