### ISSUE TITLE
About the pre-trained CAM weight you provided.

### ISSUE THREAD

**Issue by diaodiao317** [yiping-wang/c2am#11]
Sorry to bother you again. I recently made some attempts referring to recam and your code framework. At the beginning, I used the cam pre-trained weights provided by you in the network disk to conduct experiments, but when I tried to use ordinary CAM (such as the most original CAM in IRN), I could not achieve good experimental results. I measured the weight of the cam you provided and the IOU is about 49.34, while the official CAM is usually only about 48.8. I would like to ask how you trained such a good CAM pre-training weight. Did you tune hyperparameters or add additional losses? This is really important to me.
Looking forward to your reply. Thank you!
![image](https://github.com/yiping-wang/c2am/assets/56783070/3ded4722-c52c-4d78-872a-e0f2f56b3f7d)
this one

**Comment by str-ywang** [comment]
I don't think I did anything special to make the baseline better. I vaguely recall that I trained once and the numbers look fine and that's about it. 

I followed this [work](https://github.com/jiwoon-ahn/irn/tree/master/net) with its default settings to obtain `resnet50_cam.pth`, if I recall correctly.

**Comment by yiping-wang** [comment]
I don't think I did anything special to make the baseline better. I vaguely recall that I trained once and the numbers look fine and that's about it.

I followed this [work](https://github.com/jiwoon-ahn/irn/tree/master/net) with its default settings to obtain `resnet50_cam.pth`, if I recall correctly.

**Comment by diaodiao317** [comment]
Ok, I will try again. Thank you for your reply.
